FROM opensearchproject/opensearch:2.17.1
USER root
RUN ./bin/opensearch-plugin install --batch \
      https://github.com/Aiven-Open/prometheus-exporter-plugin-for-opensearch/releases/download/2.17.1.0/prometheus-exporter-2.17.1.0.zip
RUN yum install iputils -y
USER opensearch
